apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    redis.io/role: master
  ports:
    - name: redis
      protocol: TCP
      port: 12000
      targetPort: 12000
  type: NodePort
